version: '3.9'

services:
    database:
        image: postgres
        container_name: database_barbershop
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=barbershop
            - POSTGRES_DB=barbershop
        volumes:
            - pgdata:/data/postgres

    app:
        build: .
        container_name: barbershop
        restart: always
        ports:
            - 3333:3333
            - 9229:9229
        volumes:
            - .:/usr/barbershop
        links: 
            - database
        depends_on:
            - database

volumes:
    pgdata:
        driver: local